/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.group.client;

import java.io.BufferedReader;
import java.io.FileReader;

import javax.swing.JOptionPane;

/**
 *
 * @author jesse
 */
public class FinalProLogin extends javax.swing.JFrame {

    /**
     * Creates new form FianalProLogin
     */
    public FinalProLogin() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtPass = new javax.swing.JTextField();
        BtnLog = new javax.swing.JButton();
        BtnLogExit = new javax.swing.JButton();
        BtnForgotPass = new javax.swing.JButton();
        BtnStartSignUp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtUser = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to the Houghton chat");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Enter your password");

        TxtPass.setBackground(new java.awt.Color(0, 0, 0));
        TxtPass.setForeground(new java.awt.Color(255, 255, 255));

        BtnLog.setBackground(new java.awt.Color(0, 0, 0));
        BtnLog.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnLog.setForeground(new java.awt.Color(255, 255, 255));
        BtnLog.setText("Login");
        BtnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogActionPerformed(evt);
            }
        });

        BtnLogExit.setBackground(new java.awt.Color(0, 0, 0));
        BtnLogExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnLogExit.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogExit.setText("Exit");
        BtnLogExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogExitActionPerformed(evt);
            }
        });

        BtnForgotPass.setBackground(new java.awt.Color(0, 0, 0));
        BtnForgotPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnForgotPass.setForeground(new java.awt.Color(255, 255, 255));
        BtnForgotPass.setText("Forgot your password?");
        BtnForgotPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnForgotPassActionPerformed(evt);
            }
        });

        BtnStartSignUp.setBackground(new java.awt.Color(0, 0, 0));
        BtnStartSignUp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnStartSignUp.setForeground(new java.awt.Color(255, 255, 255));
        BtnStartSignUp.setText("Sign up");
        BtnStartSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStartSignUpActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Don't have an account?");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Enter your username");

        TxtUser.setBackground(new java.awt.Color(0, 0, 0));
        TxtUser.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnStartSignUp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnForgotPass))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(TxtPass)
                                    .addComponent(BtnLog)
                                    .addComponent(jLabel5)
                                    .addComponent(TxtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(56, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(BtnLogExit)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLogExit)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnForgotPass)
                    .addComponent(BtnStartSignUp))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogActionPerformed
        // TODO add your handling code here:

//        This section checks to make sure your username and password are correct if not it makes you try again or asks if you have an account
        try {
            BufferedReader buff = new BufferedReader(new FileReader("loginInfo.txt"));
            String user = buff.readLine();
            String pass = buff.readLine();
            if (user != null && pass != null) {
                if (TxtPass.getText().equals(pass) && TxtUser.getText().equals(user)) {
                    FinalProGUI proGUI = new FinalProGUI();
                    proGUI.setVisible(true);
                    this.dispose();
                } else if (TxtUser.getText().equals(user) && !TxtPass.getText().equals(pass)) {
                    JOptionPane.showMessageDialog(null, "Your password is incorrect, try again!");
                    TxtPass.setText("");
                    TxtUser.setText("");
                } else if (!TxtUser.getText().equals(user) && TxtPass.getText().equals(pass)) {
                    JOptionPane.showMessageDialog(null, "Your username is incorrect, try again!");
                    TxtPass.setText("");
                    TxtUser.setText("");
                }
                else {
                    JOptionPane.showMessageDialog(null, "Your username and password are incorrect, try again!");
                    TxtPass.setText("");
                    TxtUser.setText("");
                }
            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "You do not have an account, sign up below");
        }


    }//GEN-LAST:event_BtnLogActionPerformed

    private void BtnLogExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogExitActionPerformed
        // TODO add your handling code here:

//        This section exits the app once confirming your choice
        int res = JOptionPane.showConfirmDialog(rootPane, "This will exit the application would you like to continue?");
        if (res == JOptionPane.YES_OPTION) {
            this.dispose();
        } else {

        }

    }//GEN-LAST:event_BtnLogExitActionPerformed

    private void BtnStartSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStartSignUpActionPerformed
        // TODO add your handling code here:

//        This section opens up the signup app
        this.setVisible(false);
        FinalProSignUp signUp = new FinalProSignUp();
        signUp.setVisible(true);
    }//GEN-LAST:event_BtnStartSignUpActionPerformed

    private void BtnForgotPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnForgotPassActionPerformed
        // TODO add your handling code here:

//        This section opens up the app to reset passwords or usernames
        FinalProResetPass reset = new FinalProResetPass();
        reset.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BtnForgotPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalProLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalProLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalProLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalProLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalProLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnForgotPass;
    private javax.swing.JButton BtnLog;
    private javax.swing.JButton BtnLogExit;
    private javax.swing.JButton BtnStartSignUp;
    private javax.swing.JTextField TxtPass;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
