/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.group.client;

import com.jcraft.jsch.JSch;
import com.jcraft.jsch.Session;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author jesse
 */
public class FinalProGUI extends javax.swing.JFrame {
// These are the nessary credintials for use of the server and OLlama

    String username = "java_noob";
    String password = "nerdy4ever!";
    String host = "ds-gpu1";
    int port = 22; // Default SSH port
    String remoteHost = "localhost";//"remote_host";
    int remotePort = 11434; // Example: MySQL port
    int localPort = 11434;
    Session session = null;
//These define the nessary objects for using the chat
    private BufferedReader reader;
    private BufferedWriter writer;
    private Socket socket;
    MakeNewChat PChat;

    /**
     * Creates new form FinalProGUI
     */
    public FinalProGUI() {
//        MakeNewChat chat = new MakeNewChat();
//        chat.setVisible(false);
        initComponents();
        TxtAMsg.setEditable(false);

    }

    public FinalProGUI(MakeNewChat PChat) {
//        MakeNewChat chat = new MakeNewChat();
//        chat.setVisible(false);
        initComponents();
        this.PChat = PChat;
        TxtAMsg.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnSend = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BtnAI = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtARes = new javax.swing.JTextArea();
        BtnLeaveChat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtAMsg = new javax.swing.JTextArea();
        BtnConnect = new javax.swing.JButton();
        BtnNewChat = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Chat with friends");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Enter your message");

        BtnSend.setBackground(new java.awt.Color(0, 0, 0));
        BtnSend.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnSend.setForeground(new java.awt.Color(255, 255, 255));
        BtnSend.setText("Send");
        BtnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSendActionPerformed(evt);
            }
        });

        BtnExit.setBackground(new java.awt.Color(0, 0, 0));
        BtnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnExit.setForeground(new java.awt.Color(255, 255, 255));
        BtnExit.setText("Exit");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("No one online?");

        BtnAI.setBackground(new java.awt.Color(0, 0, 0));
        BtnAI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnAI.setForeground(new java.awt.Color(255, 255, 255));
        BtnAI.setText("Chat with AI");
        BtnAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAIActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Messages will appear here");

        TxtARes.setBackground(new java.awt.Color(0, 0, 0));
        TxtARes.setColumns(20);
        TxtARes.setForeground(new java.awt.Color(255, 255, 255));
        TxtARes.setRows(5);
        jScrollPane1.setViewportView(TxtARes);

        BtnLeaveChat.setBackground(new java.awt.Color(0, 0, 0));
        BtnLeaveChat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnLeaveChat.setForeground(new java.awt.Color(255, 255, 255));
        BtnLeaveChat.setText("Leave chat");
        BtnLeaveChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLeaveChatActionPerformed(evt);
            }
        });

        TxtAMsg.setBackground(new java.awt.Color(0, 0, 0));
        TxtAMsg.setColumns(20);
        TxtAMsg.setForeground(new java.awt.Color(255, 255, 255));
        TxtAMsg.setRows(5);
        jScrollPane2.setViewportView(TxtAMsg);

        BtnConnect.setBackground(new java.awt.Color(0, 0, 0));
        BtnConnect.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnConnect.setForeground(new java.awt.Color(255, 255, 255));
        BtnConnect.setText("Connect to chat");
        BtnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConnectActionPerformed(evt);
            }
        });

        BtnNewChat.setBackground(new java.awt.Color(0, 0, 0));
        BtnNewChat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnNewChat.setForeground(new java.awt.Color(255, 255, 255));
        BtnNewChat.setText("Private chat");
        BtnNewChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNewChatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnAI)
                                .addGap(110, 110, 110)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                                .addComponent(BtnExit))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnConnect)
                                        .addGap(0, 319, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnSend)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BtnNewChat)
                                            .addComponent(BtnLeaveChat)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BtnExit)
                    .addComponent(jLabel5)
                    .addComponent(BtnAI))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnConnect)
                        .addGap(69, 69, 69)
                        .addComponent(BtnNewChat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnLeaveChat)
                            .addComponent(BtnSend)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAIActionPerformed
        // TODO add your handling code here:

//        This section connects to OLlama and opens the AI chat screen
        try {
            JSch jsch = new JSch();
            session = jsch.getSession(username, host, port);
            session.setPassword(password);
            Properties config = new Properties();
            config.put("StrictHostKeyChecking", "no");
            session.setConfig(config);
            session.connect();
            int assignedPort = session.setPortForwardingL(localPort, remoteHost, remotePort);
            System.out.println("Tunnel established: localhost:" + assignedPort + " -> " + remoteHost + ":" + remotePort);
        } catch (Exception e) {
        }
        FinalProAI ai = new FinalProAI(this);
        ai.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnAIActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        // TODO add your handling code here:

//        This section closes the app after confirming your choice, it also disconects from the AI and the chat server  
        int res = JOptionPane.showConfirmDialog(rootPane, "This will exit the application would you like to continue?");
        if (res == JOptionPane.YES_OPTION) {
            if (session != null) {
                session.disconnect();
            }

            this.dispose();
            closeConnection();
        } else {

        }

    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnLeaveChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLeaveChatActionPerformed
        // TODO add your handling code here:

//        This allows you to exit the chat if you want
        if (writer != null && reader != null && socket!= null) {
            closeConnection();
        }

    }//GEN-LAST:event_BtnLeaveChatActionPerformed

    private void BtnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSendActionPerformed
        // TODO add your handling code here:
//        This section calls the sendMessage method to send messages to the chat
        sendMessage();
    }//GEN-LAST:event_BtnSendActionPerformed

    private void BtnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConnectActionPerformed
        // TODO add your handling code here:
        try {
            connectToServer();
            BtnConnect.setText("Connected");
            listenForMessages();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_BtnConnectActionPerformed

    private void BtnNewChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNewChatActionPerformed
        // TODO add your handling code here:
//        This first makes sure that you want to exit the mainscreen, then opes the seprate app to make a private app
        int res = JOptionPane.showConfirmDialog(rootPane, "This will exit the mainscreen, would you like to continue?");
        if (res == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            MakeNewChat newChat = new MakeNewChat(this);
            newChat.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_BtnNewChatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalProGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalProGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalProGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalProGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalProGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAI;
    private javax.swing.JButton BtnConnect;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnLeaveChat;
    private javax.swing.JButton BtnNewChat;
    private javax.swing.JButton BtnSend;
    private javax.swing.JTextArea TxtAMsg;
    private javax.swing.JTextArea TxtARes;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
public void connectToServer() {
//      This method connects the server, has you enter a username and then listens for messages 
        try {
            socket = new Socket("10.53.2.212", 6000);
            reader = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            writer = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()));

            username = JOptionPane.showInputDialog(this, "Enter the name you would like to be seen as:");
            if (username.equals("")) {
                username = JOptionPane.showInputDialog(this, "You need a name try again.");
            } else {
                writer.write(username);
                writer.newLine();
                writer.flush();

                TxtAMsg.append("You are now connected as " + username + "\n");

                listenForMessages();
            }

        } catch (IOException e) {
            System.out.println(e);
        }
    }

    public void listenForMessages() {
//      This method opens a new thread and listens for messages
        new Thread(() -> {
            try {
                String message;
                while ((message = reader.readLine()) != null) {
                    TxtAMsg.append(message + "\n");
                }
            } catch (IOException e) {
                System.out.println(e);
            }
        }).start();
    }

    public void sendMessage() {
//      This method gets the users message and sends it, it checks if there is a private chat open
        String message = TxtARes.getText();
        if (message.isEmpty()) {
            return;
        }
        if (PChat != null && PChat.person != null && !message.isEmpty()) {
            message = "@" + PChat.person + " " + message;
        }
        try {

            writer.write(message);
            writer.newLine();
            writer.flush();

            TxtAMsg.append("You: " + message + "\n");
            TxtARes.setText("");

            if (message.equalsIgnoreCase("exit")) {
                closeConnection();
            }
        } catch (IOException e) {
            System.out.println(e);
        }
    }

    public void closeConnection() {
//      This method closes the connection a disconnects 
        try {
            writer.close();
            reader.close();
            socket.close();
            BtnConnect.setText("Connect to chat");
            TxtAMsg.setText("");
        } catch (IOException e) {
            System.out.println(e);
        }
    }

}
