/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.group.client;

import java.util.ArrayList;
import javax.swing.JOptionPane;

import org.json.JSONObject;

/**
 *
 * @author jesse
 */
public class FinalProAI extends javax.swing.JFrame {

    ArrayList<String> history = new ArrayList<>();
    FinalProGUI mainScreen;
    /**
     * Creates new form FinalProAI
     */
    
    public FinalProAI() {
        initComponents();
        TxtAResAI1.setEditable(false);
    }

    public FinalProAI(FinalProGUI mainScreen) {
        this.mainScreen = mainScreen;
        initComponents();
        TxtAResAI1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TxtAResAI = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnAIExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAProm = new javax.swing.JTextArea();
        BtnSendAI = new javax.swing.JButton();
        BtnDelAIRes = new javax.swing.JButton();
        BtnExitToMain = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtAResAI1 = new javax.swing.JTextArea();

        jLabel2.setText("jLabel2");

        TxtAResAI.setBackground(new java.awt.Color(0, 0, 0));
        TxtAResAI.setForeground(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Chat with AI");

        BtnAIExit.setBackground(new java.awt.Color(0, 0, 0));
        BtnAIExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnAIExit.setForeground(new java.awt.Color(255, 255, 255));
        BtnAIExit.setText("Exit");
        BtnAIExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAIExitActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Enter your message");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Response will appear here");

        TxtAProm.setBackground(new java.awt.Color(0, 0, 0));
        TxtAProm.setColumns(20);
        TxtAProm.setForeground(new java.awt.Color(255, 255, 255));
        TxtAProm.setRows(5);
        jScrollPane1.setViewportView(TxtAProm);

        BtnSendAI.setBackground(new java.awt.Color(0, 0, 0));
        BtnSendAI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnSendAI.setForeground(new java.awt.Color(255, 255, 255));
        BtnSendAI.setText("Send");
        BtnSendAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSendAIActionPerformed(evt);
            }
        });

        BtnDelAIRes.setBackground(new java.awt.Color(0, 0, 0));
        BtnDelAIRes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnDelAIRes.setForeground(new java.awt.Color(255, 255, 255));
        BtnDelAIRes.setText("Delete response");
        BtnDelAIRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelAIResActionPerformed(evt);
            }
        });

        BtnExitToMain.setBackground(new java.awt.Color(0, 0, 0));
        BtnExitToMain.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnExitToMain.setForeground(new java.awt.Color(255, 255, 255));
        BtnExitToMain.setText("Exit to main screen");
        BtnExitToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitToMainActionPerformed(evt);
            }
        });

        TxtAResAI1.setBackground(new java.awt.Color(0, 0, 0));
        TxtAResAI1.setColumns(20);
        TxtAResAI1.setForeground(new java.awt.Color(255, 255, 255));
        TxtAResAI1.setRows(5);
        jScrollPane2.setViewportView(TxtAResAI1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnExitToMain, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnDelAIRes, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(164, 164, 164)
                        .addComponent(BtnAIExit))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnSendAI)
                        .addGap(0, 127, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAIExit)
                    .addComponent(jLabel1))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnExitToMain)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(BtnDelAIRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSendAI))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAIExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAIExitActionPerformed
        // TODO add your handling code here:

//      This confirms that you want to log out 
        int res = JOptionPane.showConfirmDialog(rootPane, "This will log you out, would you like to continue?");
        if (res == JOptionPane.YES_OPTION) {
            FinalProGUI proGUI = new FinalProGUI();
            proGUI.dispose();
            this.dispose();
        } else {

        }
    }//GEN-LAST:event_BtnAIExitActionPerformed

    private void BtnExitToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitToMainActionPerformed
        // TODO add your handling code here:
        
//      This confirms that you want to exit to the main chat 
        int res = JOptionPane.showConfirmDialog(rootPane, "This will exit the application would you like to continue?");
        if (res == JOptionPane.YES_OPTION) {
            mainScreen.setVisible(true);
            this.dispose();
        } else {

        }

    }//GEN-LAST:event_BtnExitToMainActionPerformed

    private void BtnDelAIResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelAIResActionPerformed
        // TODO add your handling code here:
        
//      This deletes the AI's responce 
        TxtAResAI1.setText("");

    }//GEN-LAST:event_BtnDelAIResActionPerformed

    private void BtnSendAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSendAIActionPerformed
        // TODO add your handling code here:
        
//      This section gives the sends your promt to the AI, it also saves your promts and the AI's responces to allow for a conversation 
        history.add("User: " + TxtAProm.getText());
        String allProms = String.join("\n", history);
        String[] key = {"llama3.2", allProms};
        TxtAProm.setText("");
        String res = FinalProConAi.sendPOST(key);
//        System.out.println(history);
//        System.out.println("LLM Response: " + res);
        JSONObject jsonObject = new JSONObject(res);
        String texts = jsonObject.getString("response");
        history.add("AI: " + jsonObject.getString("response"));
        TxtAResAI1.setText(texts);
    }//GEN-LAST:event_BtnSendAIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalProAI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalProAI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalProAI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalProAI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalProAI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAIExit;
    private javax.swing.JButton BtnDelAIRes;
    private javax.swing.JButton BtnExitToMain;
    private javax.swing.JButton BtnSendAI;
    private javax.swing.JTextArea TxtAProm;
    private javax.swing.JTextField TxtAResAI;
    private javax.swing.JTextArea TxtAResAI1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
